baseURL = "https://phelipetls.github.io"
languageCode = "en-us"
title = "Phelipe Teles"
assetsDir = "assets"
summaryLength = 20
Paginate = 5

[taxonomies]
  category = "categories"
  tag = "tags"
  tech = "techs"

[markup]
  [markup.highlight]
    style = "lovelace"
