baseURL = "https://phelipetls.github.io"
languageCode = "en-us"
title = "Phelipe Teles"
assetsDir = "assets"
summaryLength = 20
Paginate = 5

[params]
  description = "A blog to share my interests on programming, statistics and more"

[taxonomies]
  category = "categories"
  tag = "tags"
  software = "softwares"

[markup]
  [markup.highlight]
    style = "lovelace"
