baseURL = "https://phelipetls.github.io"
languageCode = "en-us"
title = "Phelipe Teles"
assetsDir = "assets"
summaryLength = 20

DefaultContentLanguage = "en"

[params]
  description = "A blog to share my interests on programming, statistics and more"

[languages]
  [languages.en]
    LanguageName = "English"
    weight = 1
  [languages.pt]
    LanguageName = "Português"
    weight = 2
    [languages.pt.params]
      description = "Um blog para compartilhar meus interesses em programação, estatística e mais"

[taxonomies]
  category = "categories"
  tag = "tags"
  software = "softwares"

[markup]
  [markup.highlight]
    style = "lovelace"

[menu]
  [[menu.main]]
  identifier = "Posts"
  name = "Posts"
  url = "/posts"
  weight = -3

  [[menu.main]]
  identifier = "Projects"
  name = "Projects"
  url = "/projects"
  weight = -2

  [[menu.main]]
  identifier = "Archive"
  name = "Archive"
  url = "/archive"
  weight = -1
