baseURL = "https://phelipetls.github.io"
languageCode = "en-us"
title = "Phelipe Teles"
assetsDir = "assets"
summaryLength = 20
pygmentsUseClasses = true

DefaultContentLanguage = "en"

[build]
  writeStats = true

[params]
  description = "A blog to share my interests (mostly programming)"
  email = "phelipe_teles@hotmail.com"
  linkedin = "https://linkedin.com/in/phelipeteles"
  github = "https://github.com/phelipetls"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.pt]
    languageName = "Português"
    weight = 2
    [languages.pt.params]
      description = "Um blog para compartilhar meus interesses em programação, estatística e mais"
      htmlLang = "pt-BR"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
    identifier = "resume-download"
    name = "Resumé"
    weight = 9999
