name: Deploy website to GitHub Pages on push

on:
  push:
    branches:
      master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'

      - run: npm ci

      - run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          external_repository: phelipetls/phelipetls.github.io
          publish_branch: master
          personal_token: ${{ secrets.TOKEN }}
