name: Deploy website to GitHub Pages on push

on:
  push:
    branches: master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - run: npm ci

      - name: Run tests
        run: npm run test
        env:
          CYPRESS_video: false

      - name: Archive Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          external_repository: phelipetls/phelipetls.github.io
          publish_branch: master
          personal_token: ${{ secrets.TOKEN }}
