name: Deploy website to GitHub Pages on push

on:
  push:
    branches:
      master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'

      - run: npm ci

      - run: hugo

      - name: Send e-mail to subscribers about new blog post
        run: node ./scripts/send-new-blog-post-email.js
        env:
          BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          external_repository: phelipetls/phelipetls.github.io
          publish_branch: master
          personal_token: ${{ secrets.TOKEN }}
